# Creating initial users
pass = '12345678'
User.where(first_name: 'Andrei', last_name: 'Bondarev', email: 'andrei.bondarev13@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1)
User.where(first_name: 'James', last_name: 'Flowers', email: 'jflowers@me.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1)
User.where(first_name: 'Matt', last_name: 'McCrea', email: 'rwemerson0386@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1)
User.where(first_name: 'Chihiro', last_name: 'Kawana', email: 'chihiro.kawana107@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1)
User.where(first_name: 'Kevin', last_name: 'Morrison', email: 'k.francis.morrison@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1)
User.where(first_name: 'Admin', last_name: 'Steve', email: 'admin@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :administrator)

Period.where(period_name: 'Period 1').first_or_create(start_time: "07:30", end_time: "08:25")
Period.where(period_name: 'Period 2').first_or_create(start_time: "08:30", end_time: "09:25")
Period.where(period_name: 'Period 3').first_or_create(start_time: "09:30", end_time: "10:25")
Period.where(period_name: 'Period 4').first_or_create(start_time: "10:30", end_time: "11:25")
Period.where(period_name: 'Period 5').first_or_create(start_time: "11:30", end_time: "12:25")
Period.where(period_name: 'Period 6').first_or_create(start_time: "12:30", end_time: "13:25")
Period.where(period_name: 'Period 7').first_or_create(start_time: "13:30", end_time: "14:25")
Period.where(period_name: 'Period 8').first_or_create(start_time: "14:30", end_time: "15:25")
Period.where(period_name: 'Period 9').first_or_create(start_time: "15:30", end_time: "16:25")

# Additional Seed users
User.where(first_name: 'Carole', last_name: 'Curtis', email: 'ccurtis@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :teacher)
User.where(first_name: 'Forrest', last_name: 'Berry', email: 'fberry@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :teacher)
User.where(first_name: 'Raquel', last_name: 'Morgan', email: 'rmorgan@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :teacher)
User.where(first_name: 'Cody', last_name: 'Cook', email: 'ccook@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :teacher)
User.where(first_name: 'Estelle', last_name: 'Gibson', email: 'egibson@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :teacher)
User.where(first_name: 'Nicole', last_name: 'Howell', email: 'nhowell@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :teacher)
User.where(first_name: 'Francis', last_name: 'Patterson', email: 'fpatterson@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :teacher)
User.where(first_name: 'Nelson', last_name: 'Brewer', email: 'nbrewer@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :teacher)
User.where(first_name: 'Miranda', last_name: 'Vargas', email: 'mvargas@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :teacher)
User.where(first_name: 'Joyce', last_name: 'Richards', email: 'jrichards@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :teacher)

# Service providers
User.where(first_name: 'Joe', last_name: 'Smith', email: 'jsmith@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :service_provider)
User.where(first_name: 'Nick', last_name: 'Stoney', email: 'nstoney@gmail.com').first_or_create(password: pass, password_confirmation: pass, organization_id: 1, role: :service_provider)

# Carole Curtis
UsersPeriod.where(user_id: User.where(email: 'ccurtis@gmail.com').first.id, period_id: Period.where(period_name: 'Period 1').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'ccurtis@gmail.com').first.id, period_id: Period.where(period_name: 'Period 2').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'ccurtis@gmail.com').first.id, period_id: Period.where(period_name: 'Period 3').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'ccurtis@gmail.com').first.id, period_id: Period.where(period_name: 'Period 4').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'ccurtis@gmail.com').first.id, period_id: Period.where(period_name: 'Period 5').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'ccurtis@gmail.com').first.id, period_id: Period.where(period_name: 'Period 6').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'ccurtis@gmail.com').first.id, period_id: Period.where(period_name: 'Period 7').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'ccurtis@gmail.com').first.id, period_id: Period.where(period_name: 'Period 8').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'ccurtis@gmail.com').first.id, period_id: Period.where(period_name: 'Period 9').first.id).first_or_create(is_planning: false)

# Forrest Berry
UsersPeriod.where(user_id: User.where(email: 'fberry@gmail.com').first.id, period_id: Period.where(period_name: 'Period 1').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'fberry@gmail.com').first.id, period_id: Period.where(period_name: 'Period 2').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'fberry@gmail.com').first.id, period_id: Period.where(period_name: 'Period 3').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'fberry@gmail.com').first.id, period_id: Period.where(period_name: 'Period 4').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'fberry@gmail.com').first.id, period_id: Period.where(period_name: 'Period 5').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'fberry@gmail.com').first.id, period_id: Period.where(period_name: 'Period 6').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'fberry@gmail.com').first.id, period_id: Period.where(period_name: 'Period 7').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'fberry@gmail.com').first.id, period_id: Period.where(period_name: 'Period 8').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'fberry@gmail.com').first.id, period_id: Period.where(period_name: 'Period 9').first.id).first_or_create(is_planning: false)

# Racheal Morgan
UsersPeriod.where(user_id: User.where(email: 'rmorgan@gmail.com').first.id, period_id: Period.where(period_name: 'Period 1').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'rmorgan@gmail.com').first.id, period_id: Period.where(period_name: 'Period 2').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'rmorgan@gmail.com').first.id, period_id: Period.where(period_name: 'Period 3').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'rmorgan@gmail.com').first.id, period_id: Period.where(period_name: 'Period 4').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'rmorgan@gmail.com').first.id, period_id: Period.where(period_name: 'Period 5').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'rmorgan@gmail.com').first.id, period_id: Period.where(period_name: 'Period 6').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'rmorgan@gmail.com').first.id, period_id: Period.where(period_name: 'Period 7').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'rmorgan@gmail.com').first.id, period_id: Period.where(period_name: 'Period 8').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'rmorgan@gmail.com').first.id, period_id: Period.where(period_name: 'Period 9').first.id).first_or_create(is_planning: true)

# Cody Cook
UsersPeriod.where(user_id: User.where(email: 'ccook@gmail.com').first.id, period_id: Period.where(period_name: 'Period 1').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'ccook@gmail.com').first.id, period_id: Period.where(period_name: 'Period 2').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'ccook@gmail.com').first.id, period_id: Period.where(period_name: 'Period 3').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'ccook@gmail.com').first.id, period_id: Period.where(period_name: 'Period 4').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'ccook@gmail.com').first.id, period_id: Period.where(period_name: 'Period 5').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'ccook@gmail.com').first.id, period_id: Period.where(period_name: 'Period 6').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'ccook@gmail.com').first.id, period_id: Period.where(period_name: 'Period 7').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'ccook@gmail.com').first.id, period_id: Period.where(period_name: 'Period 8').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'ccook@gmail.com').first.id, period_id: Period.where(period_name: 'Period 9').first.id).first_or_create(is_planning: true)

# Estelle Gibson
UsersPeriod.where(user_id: User.where(email: 'egibson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 1').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'egibson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 2').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'egibson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 3').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'egibson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 4').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'egibson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 5').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'egibson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 6').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'egibson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 7').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'egibson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 8').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'egibson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 9').first.id).first_or_create(is_planning: false)

# Nicole Howell
UsersPeriod.where(user_id: User.where(email: 'nhowell@gmail.com').first.id, period_id: Period.where(period_name: 'Period 1').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'nhowell@gmail.com').first.id, period_id: Period.where(period_name: 'Period 2').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'nhowell@gmail.com').first.id, period_id: Period.where(period_name: 'Period 3').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'nhowell@gmail.com').first.id, period_id: Period.where(period_name: 'Period 4').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'nhowell@gmail.com').first.id, period_id: Period.where(period_name: 'Period 5').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'nhowell@gmail.com').first.id, period_id: Period.where(period_name: 'Period 6').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'nhowell@gmail.com').first.id, period_id: Period.where(period_name: 'Period 7').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'nhowell@gmail.com').first.id, period_id: Period.where(period_name: 'Period 8').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'nhowell@gmail.com').first.id, period_id: Period.where(period_name: 'Period 9').first.id).first_or_create(is_planning: false)

# Francis Patterson
UsersPeriod.where(user_id: User.where(email: 'fpatterson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 1').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'fpatterson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 2').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'fpatterson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 3').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'fpatterson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 4').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'fpatterson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 5').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'fpatterson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 6').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'fpatterson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 7').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'fpatterson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 8').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'fpatterson@gmail.com').first.id, period_id: Period.where(period_name: 'Period 9').first.id).first_or_create(is_planning: false)

# Nelson Brewer
UsersPeriod.where(user_id: User.where(email: 'nbrewer@gmail.com').first.id, period_id: Period.where(period_name: 'Period 1').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'nbrewer@gmail.com').first.id, period_id: Period.where(period_name: 'Period 2').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'nbrewer@gmail.com').first.id, period_id: Period.where(period_name: 'Period 3').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'nbrewer@gmail.com').first.id, period_id: Period.where(period_name: 'Period 4').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'nbrewer@gmail.com').first.id, period_id: Period.where(period_name: 'Period 5').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'nbrewer@gmail.com').first.id, period_id: Period.where(period_name: 'Period 6').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'nbrewer@gmail.com').first.id, period_id: Period.where(period_name: 'Period 7').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'nbrewer@gmail.com').first.id, period_id: Period.where(period_name: 'Period 8').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'nbrewer@gmail.com').first.id, period_id: Period.where(period_name: 'Period 9').first.id).first_or_create(is_planning: false)

# Miranda Vargas
UsersPeriod.where(user_id: User.where(email: 'mvargas@gmail.com').first.id, period_id: Period.where(period_name: 'Period 1').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'mvargas@gmail.com').first.id, period_id: Period.where(period_name: 'Period 2').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'mvargas@gmail.com').first.id, period_id: Period.where(period_name: 'Period 3').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'mvargas@gmail.com').first.id, period_id: Period.where(period_name: 'Period 4').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'mvargas@gmail.com').first.id, period_id: Period.where(period_name: 'Period 5').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'mvargas@gmail.com').first.id, period_id: Period.where(period_name: 'Period 6').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'mvargas@gmail.com').first.id, period_id: Period.where(period_name: 'Period 7').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'mvargas@gmail.com').first.id, period_id: Period.where(period_name: 'Period 8').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'mvargas@gmail.com').first.id, period_id: Period.where(period_name: 'Period 9').first.id).first_or_create(is_planning: false)

# Joyce Richards
UsersPeriod.where(user_id: User.where(email: 'jrichards@gmail.com').first.id, period_id: Period.where(period_name: 'Period 1').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'jrichards@gmail.com').first.id, period_id: Period.where(period_name: 'Period 2').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'jrichards@gmail.com').first.id, period_id: Period.where(period_name: 'Period 3').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'jrichards@gmail.com').first.id, period_id: Period.where(period_name: 'Period 4').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'jrichards@gmail.com').first.id, period_id: Period.where(period_name: 'Period 5').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'jrichards@gmail.com').first.id, period_id: Period.where(period_name: 'Period 6').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'jrichards@gmail.com').first.id, period_id: Period.where(period_name: 'Period 7').first.id).first_or_create(is_planning: true)
UsersPeriod.where(user_id: User.where(email: 'jrichards@gmail.com').first.id, period_id: Period.where(period_name: 'Period 8').first.id).first_or_create(is_planning: false)
UsersPeriod.where(user_id: User.where(email: 'jrichards@gmail.com').first.id, period_id: Period.where(period_name: 'Period 9').first.id).first_or_create(is_planning: false)
